language: python

compiler:
  - gcc
  - clang

install:
  - pip install tox

before_script:
  - cd lib
  - wget https://googledrive.com/host/0B2gfQTHH9447fk1OWTM1OFMxUkMyajR0QUZ2WFdNZEc3d2kxM3RrM3hobnJzSTA0WlpiZ28/cmake-3.2.2-Linux-x86_64.tar.gz
  - tar -zxvf cmake-3.2.2-Linux-x86_64.tar.gz
  - mkdir debug

script:
  - cd debug
  - ../cmake-3.2.2-Linux-x86_64/bin/cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make
  - ./test
  - cd ..
  - travis_wait tox -vvv